AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cigar Vault

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  CigarVaultFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Environment:
        Variables:
          ANTHROPIC_API_KEY: '{{resolve:ssm:/cigar-vault/ANTHROPIC_API_KEY}}'
          ELEVENLABS_API_KEY: '{{resolve:ssm:/cigar-vault/ELEVENLABS_API_KEY}}'
          ELEVENLABS_VOICE_ID: '{{resolve:ssm:/cigar-vault/ELEVENLABS_VOICE_ID}}'
      Events:
        CigarVaultApi:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootPath:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        WarmUp:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
       
    Metadata:
      DockerTag: cigar-vault
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  CigarVaultApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"